#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from naoqi import ALProxy

pip = '127.0.0.1'
pport = 9559

def callback(data):
	rospy.loginfo(rospy.get_caller_id() + data.data)
	tts=ALProxy('ALTextToSpeech',pip,pport)
	tts.say(data.data)
def listener():
	rospy.init_node('react',anonymous=True)
	rospy.Subscriber('sentence',String,callback)
	rospy.spin()

if __name__=='__main__':
	try:
	    listener()
	except rospy.ROSInterruptException:
	    pass
