#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import speech_recognition as sr
import rospy
from std_msgs.msg import String

r = sr.Recognizer()
m = sr.Microphone()

pub = rospy.Publisher('sentence', String, queue_size = 10)
rospy.init_node('user_speak',anonymous=True)
#rate = rospy.Rate(10)
try:
    print("A moment of silence, please...")
    with m as source: r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while not rospy.is_shutdown():
        print("Say something!")
        with m as source: audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)
             # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes:  # this version of Python uses bytes for strings (Python 2)
		print('You said {}'.format(value).encode("utf-8"))
		pub.publish('{}'.format(value).encode("utf-8"))
		#rate.sleep()
            else:  # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except rospy.ROSInterruptException:
    sys.exit(0)
